name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Node.js to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AWS_KEY }}

      - name: Remove path
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_HOST }} "rm -rf /home/ubuntu/lopoly-fe/* /home/ubuntu/lopoly-fe/.* 2>/dev/null"

      - name: Use Node.js 22.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_LOPOLY_FE }}" > .env
          
      - name: Install and build locally
        run: |
          npm install
          npm run build

      - name: Copy to EC2
        run: |
         rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./dist/ ubuntu@${{ secrets.AWS_HOST }}:/home/ubuntu/lopoly-fe/
