name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Node.js to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.JEROBAS_KEY }}

      - name: Remove path
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 ${{secrets.JEROBAS_USER }}@${{ secrets.JEROBAS_HOST }} "rm -rf /home/${{secrets.JEROBAS_USER }}/repos/lopoly-fe/* /home/${{secrets.JEROBAS_USER }}/repos/lopoly-fe/.* 2>/dev/null"

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_LOPOLY_FE }}" > .env

      - name: Install and build locally
        run: |
          npm install
          npm run build

      - name: Copy to EC2
        run: |
          rsync -avz --delete \
           -e "ssh -o StrictHostKeyChecking=no -p 2222" \
           ./dist/ ${{secrets.JEROBAS_USER}}@${{ secrets.JEROBAS_HOST }}:/home/${{secrets.JEROBAS_USER}}/repos/lopoly-fe/
